version: "2.0"
#rename to docker-compose

services:
    master: 
      image: elasticsearch:2.4.2
      environment: 
        ES_HEAP_SIZE: 512M
      mem_limit: 1g
      volumes:
        - /etc/localtime:/etc/localtime:ro
      networks:
        - devcluster
      ports: 
        - "9200:9200"
      command: "elasticsearch -Des.cluster.name=devcluster -Des.node.data=false -Des.node.master=true "
    elasticnode1:
      image: elasticsearch:2.4.2
      environment: 
        ES_HEAP_SIZE: 2g
      mem_limit: 3g
      volumes:
        - /home/ozlevka/bigdisk/data/monitor/cluster:/usr/share/elasticsearch/data
        - /etc/localtime:/etc/localtime:ro
      links: 
        - master
      command: "elasticsearch -Des.cluster.name=devcluster -Des.node.data=true -Des.node.master=false -Ddiscovery.zen.ping.unicast.hosts=master "
      networks:
        - devcluster
    elasticnode2:
      image: elasticsearch:2.4.2
      environment: 
        ES_HEAP_SIZE: 2g
      mem_limit: 3g
      volumes:
        - /home/ozlevka/bigdisk/data/monitor/cluster:/usr/share/elasticsearch/data
        - /etc/localtime:/etc/localtime:ro
      links: 
        - master
      command: "elasticsearch -Des.cluster.name=devcluster -Des.node.data=true -Des.node.master=false -Ddiscovery.zen.ping.unicast.hosts=master "
      networks:
        - devcluster
    kibana:
      image: ozlevka/kibana-sense:4.6.2
      command: kibana -e http://master:9200
      mem_limit: 512m
      volumes:
        - /etc/localtime:/etc/localtime:ro
      ports: 
        - "5601:5601"
      links:
        - master
      networks:
        - devcluster
networks:
  devcluster:
    driver: bridge